apiVersion: v1
kind: Pod
metadata:
  name: broken-app
  namespace: default
  labels:
    app: broken-app
spec:
  containers:
  - name: app
    image: nginx:nonexistent-tag  # This will cause ImagePullBackOff
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
