apiVersion: v1
kind: Pod
metadata:
  name: crashloop-app
  namespace: default
  labels:
    app: crashloop-app
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "exit 1"]  # This will cause CrashLoopBackOff
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m"
