apiVersion: v1
kind: Pod
metadata:
  name: oom-app
  namespace: default
  labels:
    app: oom-app
spec:
  containers:
  - name: app
    image: progrium/stress
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "500M"  # Will exceed memory limit
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"  # Too low - will cause OOMKilled
        cpu: "200m"
